// Decompiled with JetBrains decompiler
// Type: InfoGov.Plugins.Infogov.Expertos.ExpReporteInfogov
// Assembly: plugin-infogov, Version=1.0.0.18780, Culture=neutral, PublicKeyToken=null
// MVID: 33F9E52C-1C9C-4132-80FE-D29F95E246A9
// Assembly location: C:\nomade\para copiar\plugin-infogov.dll

using System.Text;

#nullable disable
namespace InfoGov.Plugins.Infogov.Expertos;

public class ExpReporteInfogov
{
  public StringBuilder generateHead(string Title, bool apaisado = false)
  {
    StringBuilder head = new StringBuilder();
    head.AppendLine("<!DOCTYPE HTML>");
    head.AppendLine("<html lang=\"es-ar\">");
    head.AppendLine("<head>");
    head.AppendLine("\t<meta charset=\"utf-8\"/>");
    head.AppendLine($"\t<title>{Title}</title>");
    head.AppendLine("\t<style type=\"text/css\">");
    head.AppendLine(".pagebreak { page-break-before: always; }");
    head.AppendLine("\t\thtml, body {");
    head.AppendLine("\t\t\tfont-family:Gotham Light;");
    head.AppendLine("\t\t\tfont-size:12px;");
    head.AppendLine("\t\t\tmargin:0;");
    head.AppendLine("\t\t\tpadding:0;");
    head.AppendLine("\t\t}");
    head.AppendLine("\t\t#tprinc { margin:0 auto; }");
    head.AppendLine("\t\t#theader { font-size:13px; }");
    head.AppendLine("\t\t.DataTable {");
    head.AppendLine("\t\t\tborder:solid black 1px;");
    head.AppendLine("\t\t\tborder-collapse:collapse;");
    head.AppendLine("\t\t\twidth:100%;");
    head.AppendLine("\t\t}");
    head.AppendLine("\t\t.HeaderCell {");
    head.AppendLine("\t\t\tborder:solid black 1px;");
    head.AppendLine("\t\t\tfont-weight:bold;");
    head.AppendLine("\t\t\tpadding:4px 3px 4px 3px;");
    head.AppendLine("\t\t}");
    head.AppendLine("\t\t.HeaderCell.Center { text-align:center; }");
    head.AppendLine("\t\t.HeaderCell.Left { text-align:left; }");
    head.AppendLine("\t\t.HeaderCell.Right { text-align:right; }");
    head.AppendLine("   .HeaderCell.Center.Grey { text-align:center; background-color: #D3D3D3;font-size:11px;}");
    head.AppendLine("   .HeaderCell.Center.Small { text-align:center; font-size:10px; font-weight:bold; }");
    head.AppendLine("\t\t.DataCell {");
    head.AppendLine("\t\t\tborder:solid gray 1px;");
    head.AppendLine("\t\t\tfont-family:Lucida Sans Typewriter;");
    head.AppendLine("\t\t\tfont-size:12px;");
    head.AppendLine("\t\t\tpadding:2px 3px 2px 3px;");
    head.AppendLine("\t\t}");
    head.AppendLine("\t\t.DataCell.Center { text-align:center; }");
    head.AppendLine("\t\t.DataCell.Left { text-align:left; }");
    head.AppendLine("\t\t.DataCell.Right { text-align:right; }");
    head.AppendLine("\t\t.DataCell.Center.Small { text-align:center; font-size:10px; }");
    head.AppendLine("\t\t.DataCell.Left.Small { text-align:left; ; font-size:10px;}");
    head.AppendLine("\t\t.DataCell.Right.Small { text-align:right; ; font-size:10px;}");
    head.AppendLine("\t\t.BorderlessCell {");
    head.AppendLine("\t\t\tfont-family:Lucida Sans Typewriter;");
    head.AppendLine("\t\t\tfont-size:12px;");
    head.AppendLine("\t\t\tpadding:2px 3px 2px 3px;");
    head.AppendLine("\t\t}");
    head.AppendLine("\t\t.BorderlessCell.Center { text-align:center; }");
    head.AppendLine("\t\t.BorderlessCell.Left { text-align:left; }");
    head.AppendLine("\t\t.BorderlessCell.Right { text-align:right; }");
    head.AppendLine(".Titulo1 {");
    head.AppendLine("font-family: Georgia, \"Times New Roman\", Times, serif;");
    head.AppendLine("font-size: 16px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("}");
    head.AppendLine(".Titulo2 {");
    head.AppendLine("font-family: Georgia, \"Times New Roman\", Times, serif;");
    head.AppendLine("font-size: 14px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("border: 1px solid black;");
    head.AppendLine("border-collapse: collapse;");
    head.AppendLine("}");
    head.AppendLine(".Normal {");
    head.AppendLine("font-family: Georgia, \"Times New Roman\", Times, serif;");
    head.AppendLine("font-size: 12px;");
    head.AppendLine("font-style: normal;");
    head.AppendLine("font-weight: normal;");
    head.AppendLine("font-variant: normal;");
    head.AppendLine("}");
    head.AppendLine(".Encabezado {");
    head.AppendLine("font-family: \"Times New Roman\", Times, serif;");
    head.AppendLine("font-size: 11px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #D3D3D3;");
    head.AppendLine("vertical-align: middle;");
    head.AppendLine("text-align:center;");
    head.AppendLine("}");
    head.AppendLine(".LineaDato {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("border: 1px solid black;");
    head.AppendLine("border-collapse: collapse;");
    head.AppendLine("}");
    head.AppendLine(".LDCen {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:center;");
    head.AppendLine("}");
    head.AppendLine(".margin0 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("padding-left:10px;");
    head.AppendLine("}");
    head.AppendLine(".margin2 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("padding-left:20px;");
    head.AppendLine("}");
    head.AppendLine(".margin3 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("padding-left:30px;");
    head.AppendLine("}");
    head.AppendLine(".margin4 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("padding-left:40px;");
    head.AppendLine("}");
    head.AppendLine(".margin5 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("padding-left:50px;");
    head.AppendLine("}");
    head.AppendLine(".LDIzq {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 11px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:left;");
    head.AppendLine("}");
    head.AppendLine(".LDDer {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("vertical-align: top;");
    head.AppendLine("text-align:right;");
    head.AppendLine("}");
    head.AppendLine(".Totales {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 14px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #7DC3E7;");
    head.AppendLine("}");
    head.AppendLine(".Totales2 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #9BCFEC;");
    head.AppendLine("}");
    head.AppendLine(".Totales3 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #C1E2F4;");
    head.AppendLine("}");
    head.AppendLine(".Totales4 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #DEEFFA;");
    head.AppendLine("}");
    head.AppendLine(".Totales5 {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("font-weight: bold;");
    head.AppendLine("background-color: #EDF5FC;");
    head.AppendLine("}");
    head.AppendLine(".Firmas {");
    head.AppendLine("font-family: Arial, Helvetica, sans-serif;");
    head.AppendLine("font-size: 10px;");
    head.AppendLine("font-weight: normal;");
    head.AppendLine("}");
    head.AppendLine(".Proveedor {");
    head.AppendLine("font-family: \"Courier New\", Courier, monospace;");
    head.AppendLine("font-size: 14px;");
    head.AppendLine("}");
    head.AppendLine("THEAD { display: table-header-group; }");
    head.AppendLine("\t</style>");
    head.AppendLine("</head>");
    return head;
  }
}
